#!/usr/bin/env bash

sudo dscacheutil -flushcache
rm ~/Library/Preferences/*LSSharedFileList.plist
defaults delete -g NSNavRecentPlaces

rm ~/Library/Safari/History.plist
rm ~/Library/Safari/Downloads.plist
rm ~/Library/Safari/HistoryIndex.sk
rm ~/Library/Safari/LastSession.plist
rm ~/Library/Safari/TopSites.plist
rm -rf ~/Library/Caches/com.apple.safari